### PR TITLE
day 3

### PR DESCRIPTION
**Pull request by interrogator**
Materials for day three are all here! There's a `sys.path.append()` going on at the start of the students' day three notebook, and I'm not sure what it's for, maybe obsolete, but I don't want to break everything by removing it.

Also, some of the code we'll be teaching today could be cleaned up a bit: the `parse_metadata()` function uses `continue`, which we won't have taught yet ...

### CODE REVIEW

**Comment by lachlansimpson** [comment]
More than 25 minutes of scrutiny for oversight would be handy ;P

**Comment by interrogator** [comment]
Do you like working on Sundays, Lachlan?

**Comment by lachlansimpson** [comment]
Touche

---

I'm treading carefully
but it's the time of night
the snowy light
the subway roar
and the whispered fights
exciting sights
but it's not enough
I thought it was
I wish it was

## I thought it was

You name it - The Cannanes with Explosion Robinson.

**Comment by interrogator** [comment]
Argh, our printer isn't working, can you print `resources/completed-notebooks/session-3.ipynb`??

**Comment by lachlansimpson** [comment]
yep

---

I'm treading carefully
but it's the time of night
the snowy light
the subway roar
and the whispered fights
exciting sights
but it's not enough
I thought it was
I wish it was

## I thought it was

You name it - The Cannanes with Explosion Robinson.

**Comment by interrogator** [comment]
#Thanks!

**Comment by lachlansimpson** [comment]
just one copy?

---

I'm treading carefully
but it's the time of night
the snowy light
the subway roar
and the whispered fights
exciting sights
but it's not enough
I thought it was
I wish it was

## I thought it was

You name it - The Cannanes with Explosion Robinson.

**Pull request merged**
